### ISSUE TITLE
Templating returns an INT when yaml value is all digits

### ISSUE THREAD

**Issue by michelleheh** [checkr/openmock#70]
We are getting the following error in our templated mocks:
```
failed to render condition: {{
  (.HTTPBody | regexFindFirstSubmatch "<License>([^<>]+)</License>" | eq .Values.license_number)
}}  err="template: :1:297: executing \"\" at <eq .Values.license_number>: error calling eq: incompatible types for comparison"
echo: http: response.Write on hijacked connection from io.(*multiWriter).Write (multi.go:60)
```
We are using an AbstractBehavior:

```
- key: some-template
  kind: AbstractBehavior
  values:
    license_number: G1234567
  actions:
    - reply_http:
        status_code: 200
        body: OK
  expect:
    http:
      method: POST
      path: /some-path
    condition: '{{ (.HTTPBody | regexFindFirstSubmatch "<License>([^<>]+)</License>" | eq .Values.license_number) }}
```
The mocks look like:
```
- key: some-key
  extend: some-template
  values:
    license_number: G1234567
  actions:
    - redis:
...
```
After some investigation, the problem turns out to be that one of the mocks have license_number of 000000000, and it was templated into a `int` instead of a `string`.

Would it make sense to always return a string type?

@WilsonGiese

**Comment by michelleheh** [comment]
In our case, it was not immediately clear that all digit yaml values are interpreted into an `int`, which I assume is the default behavior of the go templating. The solution is either calling `toString` before the comparison or put quotes around the values in the yaml file.

How does this look: https://github.com/checkr/openmock/pull/72

**Comment by zhouzhuojie** [comment]
Yup, that's YAML syntax for digits

```
foo: 123
bar: "123"
```
